{{- $fullName := include "helm-template.fullname" . -}}
{{- if eq .Values.kind "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helm-template.labels" . | nindent 4 }}
    {{- if .Values.additionLabels }}
    {{- toYaml .Values.additionLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.additionAnnotations }}
    {{- toYaml .Values.additionAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "helm-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-template.selectorLabels" . | nindent 8 }}
        {{- if .Values.additionLabels }}
        {{- toYaml .Values.additionLabels | nindent 8 }}
        {{- end }}
    spec:
      hostIPC: {{ .Values.hostIPC }}
      hostPID: {{ .Values.hostPID }}
      hostNetwork: {{ .Values.hostNetwork }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-template.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      containers:
        - name: {{ .Values.fullnameOverride }}
          env:
            {{- if .Values.sealedSecrets.enabled }}
            {{- if .Values.sealedSecrets.encryptedData.mapEnv }}
            {{- range .Values.sealedSecrets.encryptedData.mapEnv }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: {{ .name }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.image.tag }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- else }}
          image: "{{ .Values.image.repository }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command:
            {{- toYaml .Values.image.command | nindent 12 }}
          {{- end }}
          {{- if .Values.image.args }}
          args:
            {{- toYaml .Values.image.command | nindent 12 }}
          {{- end }}
          {{- if .Values.image.containerPort }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          {{- end }}
          {{- if .Values.image.healthCheck }}
          {{- toYaml .Values.image.healthCheck | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if and .Values.sealedSecrets.enabled .Values.sealedSecrets.encryptedData.mapFile }}
            {{- range .Values.sealedSecrets.encryptedData.mapFile}}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: true
            {{- end }}
            {{- end }}
            {{- range .Values.mountConfigmap }}
            - name: {{ $fullName }}-configmap-volume
              mountPath: {{ .path }}
              subPath: {{ .name }}
            {{- end }}
            {{- range .Values.mountPVCs }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}

        {{- if .Values.fluentd.enabled }}
        - name: fluentd
          image: "{{ .Values.fluentd.image }}"
          ports:
            - name: fluentd
              containerPort: {{ .Values.fluentd.port }}
              protocol: TCP
        {{- end }}

        {{- if .Values.sidecarContainers }}
        {{- toYaml .Values.sidecarContainers | nindent 8 }}
        {{- end }}

      volumes:
        {{- if and .Values.sealedSecrets.enabled .Values.sealedSecrets.encryptedData.mapFile }}
        {{- range .Values.sealedSecrets.encryptedData.mapFile}}
        - name: {{ .name }}
          secret: 
            secretName: {{ $fullName }}
            items:
            {{- range .files }}
              - key: {{ .name }}
                path: {{ .path | default .name }}
            {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.mountConfigmap }}
        - name: {{ $fullName }}-configmap-volume
          configMap:
            name: {{ $fullName }}-configmap
            items:
              {{- range .Values.mountConfigmap}}
              - key: {{ .name }}
                path: {{ .name }}
              {{- end }}
        {{- end }}
        {{- range .Values.mountPVCs }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
{{- end }}