{{- $fullName := include "helm-template.fullname" . -}}
{{- if eq .Values.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helm-template.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-template.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations| nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-template.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      containers:
        - name: {{ .Values.fullnameOverride }}
          env:
            {{- if .Values.sealedSecrets.enabled }}
            {{- if .Values.sealedSecrets.encryptedData.mapEnv }}
            {{- range .Values.sealedSecrets.encryptedData.mapEnv }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: {{ .name }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command: {{ .Values.image.command }}
          {{- end }}
          {{- if .Values.image.args }}
          args: {{ .Values.image.args }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          {{- if .Values.image.healthCheck }}
          {{- toYaml .Values.image.healthCheck | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if and .Values.sealedSecrets.enabled .Values.sealedSecrets.encryptedData.mapFile }}
            {{- range .Values.sealedSecrets.encryptedData.mapFile}}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: true
            {{- end }}
            {{- end }}
            {{- range .Values.mountConfigmap }}
            - name: {{ $fullName }}-configmap-volume
              mountPath: {{ .path }}
              subPath: {{ .name }}
            {{- end }}            

        {{- if .Values.fluentd.enabled }}
        - name: fluentd
          image: "{{ .Values.fluentd.image }}"
          ports:
            - name: fluentd
              containerPort: {{ .Values.fluentd.port }}
              protocol: TCP
        {{- end }}

      volumes:
        {{- if and .Values.sealedSecrets.enabled .Values.sealedSecrets.encryptedData.mapFile }}
        {{- range .Values.sealedSecrets.encryptedData.mapFile}}
        - name: {{ .name }}
          secret: 
            secretName: {{ $fullName }}
            items:
            {{- range .files }}
              - key: {{ .name }}
                path: {{ .path | default .name }}
            {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.mountConfigmap }}
        - name: {{ $fullName }}-configmap-volume
          configMap:
            name: {{ $fullName }}-configmap
            items:
              {{- range .Values.mountConfigmap}}
              - key: {{ .name }}
                path: {{ .name }}
              {{- end }}
        {{- end }}
{{- end }}