{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "helm-template.fullname" . }}
  {{- if .Values.sealedSecrets.annotations}}
  annotations:
    {{- range $key, $val := .Values.sealedSecrets.annotations }}
    {{ $key | indent 2}}: {{ $val | quote }}
    {{- end}}
  {{- end}}
spec:
  encryptedData:
  {{- with .Values.sealedSecrets.encryptedData }}
    {{- range .mapFile }}
    {{- range .files}}
    {{ .name }} : {{ .value }}
    {{- end }}
    {{- end }}
    {{- range .mapEnv }}
    {{ .name }} : {{ .value }}
    {{- end }}
  {{- end }}
  template:
    type: Opaque
	{{- with .Values.sealedSecrets.secretMetadata }}
    metadata:
	  	{{- toYaml . | nindent 6 }}
	{{- end }}
{{- end }}