{{- if .Values.image.containerPort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-template.fullname" . }}
  labels:
    {{- include "helm-template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
      name: {{ .Values.image.containerPortName }}
    {{- range .Values.extraServicePorts  }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "helm-template.selectorLabels" . | nindent 4 }}
{{- end }}